<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AddEquipamentosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /* DB::table('equipamentos')->insert(['nome' => 'Britador Móvel CCM 5030', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'CCM 5030', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2010', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00052', 'cod_operacao' => 'BM01']);
        DB::table('equipamentos')->insert(['nome' => 'Britador Móvel 62x40 / 60TS', 'descricao' => '-', 'marca_id' => '6', 'modelo' => '62x40 / 60TS', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '1994', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00055', 'cod_operacao' => 'BM02']);
        DB::table('equipamentos')->insert(['nome' => 'Caminhão Basculante Ford 6x4 2622', 'descricao' => 'Maicon', 'marca_id' => '6', 'modelo' => 'Ford 6x4 2622', 'potencia' => '14', 'tipo_potencia' => '8', 'ano_fabricacao' => '2010', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '90001', 'cod_operacao' => 'CB00']);
        DB::table('equipamentos')->insert(['nome' => 'Caminhão Basculante Ford 14.000 6x2 ', 'descricao' => 'MBJ-2780', 'marca_id' => '1', 'modelo' => 'Ford 14.000 6x2 ', 'potencia' => '12', 'tipo_potencia' => '8', 'ano_fabricacao' => '1989', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00033', 'cod_operacao' => 'CB01']);
        DB::table('equipamentos')->insert(['nome' => 'Caminhão Basculante Ford 6x4 2425', 'descricao' => 'COJ-3319', 'marca_id' => '1', 'modelo' => 'Ford 6x4 2425', 'potencia' => '14', 'tipo_potencia' => '8', 'ano_fabricacao' => '1997', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00030', 'cod_operacao' => 'CB02']);
        DB::table('equipamentos')->insert(['nome' => 'Caminhão Basculante MB 6x4 2318', 'descricao' => 'NFB-0068', 'marca_id' => '1', 'modelo' => 'MB 6x4 2318', 'potencia' => '14', 'tipo_potencia' => '8', 'ano_fabricacao' => '1995', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00064', 'cod_operacao' => 'CB03']);
        DB::table('equipamentos')->insert(['nome' => 'Caminhão Basculante Ford 6x4 2422', 'descricao' => 'COJ-8027', 'marca_id' => '1', 'modelo' => 'Ford 6x4 2422', 'potencia' => '14', 'tipo_potencia' => '8', 'ano_fabricacao' => '1997', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00025', 'cod_operacao' => 'CB04']);
        DB::table('equipamentos')->insert(['nome' => 'Caminhão Basculante Ford 6x4 2629', 'descricao' => 'QHG-6827', 'marca_id' => '1', 'modelo' => 'Ford 6x4 2629', 'potencia' => '14', 'tipo_potencia' => '8', 'ano_fabricacao' => '2015', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00026', 'cod_operacao' => 'CB05']);
        DB::table('equipamentos')->insert(['nome' => 'Caminhão Basculante Ford 6x4 2629', 'descricao' => 'QHG-68I7', 'marca_id' => '1', 'modelo' => 'Ford 6x4 2629', 'potencia' => '14', 'tipo_potencia' => '8', 'ano_fabricacao' => '2015', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00027', 'cod_operacao' => 'CB06']);
        DB::table('equipamentos')->insert(['nome' => 'Caminhão Basculante MB Axor 4144K 6x4', 'descricao' => 'DSF-9I61', 'marca_id' => '6', 'modelo' => 'MB Axor 4144K 6x4', 'potencia' => '16', 'tipo_potencia' => '8', 'ano_fabricacao' => '2007', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00012', 'cod_operacao' => 'CB07']);
        DB::table('equipamentos')->insert(['nome' => 'Caminhão Basculante Ford 6x2 1622', 'descricao' => 'MDR-8590', 'marca_id' => '6', 'modelo' => 'Ford 6x2 1622', 'potencia' => '14', 'tipo_potencia' => '8', 'ano_fabricacao' => '1998', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00036', 'cod_operacao' => 'CB08']);
        DB::table('equipamentos')->insert(['nome' => 'Caminhão Basculante MB 1621 ', 'descricao' => 'MAE-0169', 'marca_id' => '6', 'modelo' => 'MB 1621 ', 'potencia' => '14', 'tipo_potencia' => '8', 'ano_fabricacao' => '1992', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00070', 'cod_operacao' => 'CB09']);
        DB::table('equipamentos')->insert(['nome' => 'Carreta Basculante Facchini 3 eixos', 'descricao' => 'RLL-7J84', 'marca_id' => '6', 'modelo' => 'Facchini 3 eixos', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2022', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00082', 'cod_operacao' => 'CB10']);
        DB::table('equipamentos')->insert(['nome' => 'Caminhão Comboio MB 1113', 'descricao' => 'LXE-1337', 'marca_id' => '6', 'modelo' => 'MB 1113', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '1982', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00024', 'cod_operacao' => 'CC01']);
        DB::table('equipamentos')->insert(['nome' => 'Caminhão Espargidor MB 1317', 'descricao' => 'LYL-6490', 'marca_id' => '6', 'modelo' => 'MB 1317', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '1986', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00034', 'cod_operacao' => 'CE01']);
        DB::table('equipamentos')->insert(['nome' => 'Cavalo Mecânico Sinotruck 380 6x4', 'descricao' => 'MIJ-9479', 'marca_id' => '6', 'modelo' => 'Sinotruck 380 6x4', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2010', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00028', 'cod_operacao' => 'CM01']);
        DB::table('equipamentos')->insert(['nome' => 'Cavalo Mecânico MB 1634', 'descricao' => 'MIB-0D59', 'marca_id' => '6', 'modelo' => 'MB 1634', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2011', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00083', 'cod_operacao' => 'CM02']);
        DB::table('equipamentos')->insert(['nome' => 'Carro Passeio Uno Branco', 'descricao' => 'MJK-6573', 'marca_id' => '6', 'modelo' => 'Uno Branco', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2013', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00016', 'cod_operacao' => 'CP01']);
        DB::table('equipamentos')->insert(['nome' => 'Carro Passeio Uno Vermelho', 'descricao' => 'MKN-3265', 'marca_id' => '6', 'modelo' => 'Uno Vermelho', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2013', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00019', 'cod_operacao' => 'CP02']);
        DB::table('equipamentos')->insert(['nome' => 'Carro Passeio Uno Branco', 'descricao' => 'MDY-2603', 'marca_id' => '6', 'modelo' => 'Uno Branco', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2008', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00018', 'cod_operacao' => 'CP03']);
        DB::table('equipamentos')->insert(['nome' => 'Carro Passeio Gol Branco', 'descricao' => 'AMT-4H70', 'marca_id' => '6', 'modelo' => 'Gol Branco', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2005', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00035', 'cod_operacao' => 'CP04']);
        DB::table('equipamentos')->insert(['nome' => 'Carro Passeio Gol Vermelho', 'descricao' => 'MKB-6G57', 'marca_id' => '6', 'modelo' => 'Gol Vermelho', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2012', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00075', 'cod_operacao' => 'CP05']);
        DB::table('equipamentos')->insert(['nome' => 'Carreta Transporte Librelato 3 eixos', 'descricao' => 'MGR-5576', 'marca_id' => '6', 'modelo' => 'Librelato 3 eixos', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2008', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00022', 'cod_operacao' => 'CT01']);
        DB::table('equipamentos')->insert(['nome' => 'Carreta Transporte Pastre 2 eixos', 'descricao' => 'RLC-9F43', 'marca_id' => '6', 'modelo' => 'Pastre 2 eixos', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2021', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00066', 'cod_operacao' => 'CT02']);
        DB::table('equipamentos')->insert(['nome' => 'Escavadeira Hidráulica Hyundai 210 LC7', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Hyundai 210 LC7', 'potencia' => '22', 'tipo_potencia' => '5', 'ano_fabricacao' => '2008', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00039', 'cod_operacao' => 'EH01']);
        DB::table('equipamentos')->insert(['nome' => 'Escavadeira Hidráulica Case CX 220B', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Case CX 220B', 'potencia' => '22', 'tipo_potencia' => '5', 'ano_fabricacao' => '2012', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00040', 'cod_operacao' => 'EH02']);
        DB::table('equipamentos')->insert(['nome' => 'Escavadeira Hidráulica Hyundai 160 S 9B', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Hyundai 160 S 9B', 'potencia' => '18', 'tipo_potencia' => '5', 'ano_fabricacao' => '2013', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00038', 'cod_operacao' => 'EH03']);
        DB::table('equipamentos')->insert(['nome' => 'Escavadeira Hidráulica Hyundai 220 9S', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Hyundai 220 9S', 'potencia' => '22', 'tipo_potencia' => '5', 'ano_fabricacao' => '2017', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00037', 'cod_operacao' => 'EH04']);
        DB::table('equipamentos')->insert(['nome' => 'Escavadeira Hidráulica Hyundai 220 9S', 'descricao' => 'Robex', 'marca_id' => '6', 'modelo' => 'Hyundai 220 9S', 'potencia' => '22', 'tipo_potencia' => '5', 'ano_fabricacao' => '2020', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00069', 'cod_operacao' => 'EH05']);
        DB::table('equipamentos')->insert(['nome' => 'Escavadeira Hidráulica LiuGong 908', 'descricao' => 'Romac', 'marca_id' => '6', 'modelo' => 'LiuGong 908', 'potencia' => '8', 'tipo_potencia' => '5', 'ano_fabricacao' => '2022', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00073', 'cod_operacao' => 'EH06']);
        DB::table('equipamentos')->insert(['nome' => 'Fora de Estrada Randon RK 425 B', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Randon RK 425 B', 'potencia' => '14', 'tipo_potencia' => '8', 'ano_fabricacao' => '1989', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00058', 'cod_operacao' => 'FE01']);
        DB::table('equipamentos')->insert(['nome' => 'Fora de Estrada Randon RK 425 B', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Randon RK 425 B', 'potencia' => '14', 'tipo_potencia' => '8', 'ano_fabricacao' => '1995', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00059', 'cod_operacao' => 'FE02']);
        DB::table('equipamentos')->insert(['nome' => 'Fora de Estrada Volvo A25 C', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Volvo A25 C', 'potencia' => '16', 'tipo_potencia' => '8', 'ano_fabricacao' => '1994', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00071', 'cod_operacao' => 'FE03']);
        DB::table('equipamentos')->insert(['nome' => 'Grade de Discos Super Tatu 16 discos', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Super Tatu 16 discos', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '1998', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00054', 'cod_operacao' => 'GD01']);
        DB::table('equipamentos')->insert(['nome' => 'Mini Carregadeira Case 95 XT', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Case 95 XT', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2021', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00072', 'cod_operacao' => 'MC01']);
        DB::table('equipamentos')->insert(['nome' => 'Meio Fio IBM', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'IBM', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '-', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00091', 'cod_operacao' => 'MF01']);
        DB::table('equipamentos')->insert(['nome' => 'Motoniveladora Caterpillar 120H', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Caterpillar 120H', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '-', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '90002', 'cod_operacao' => 'MN00']);
        DB::table('equipamentos')->insert(['nome' => 'Motoniveladora HubeWarco 130M', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'HubeWarco 130M', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '1986', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00049', 'cod_operacao' => 'MN01']);
        DB::table('equipamentos')->insert(['nome' => 'Motoniveladora XCMG GR 180', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'XCMG GR 180', 'potencia' => '17', 'tipo_potencia' => '5', 'ano_fabricacao' => '2008', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00048', 'cod_operacao' => 'MN02']);
        DB::table('equipamentos')->insert(['nome' => 'Motoniveladora Sany SHG 190', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Sany SHG 190', 'potencia' => '17', 'tipo_potencia' => '5', 'ano_fabricacao' => '2011', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00047', 'cod_operacao' => 'MN03']);
        DB::table('equipamentos')->insert(['nome' => 'Motoniveladora New Holand 140B', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'New Holand 140B', 'potencia' => '16', 'tipo_potencia' => '5', 'ano_fabricacao' => '2007', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00046', 'cod_operacao' => 'MN04']);
        DB::table('equipamentos')->insert(['nome' => 'Motoniveladora Caterpillar 120H', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Caterpillar 120H', 'potencia' => '14', 'tipo_potencia' => '5', 'ano_fabricacao' => '2005', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00060', 'cod_operacao' => 'MN05']);
        DB::table('equipamentos')->insert(['nome' => 'Ônibus Coletivo MB 1114', 'descricao' => 'LZW-2056', 'marca_id' => '6', 'modelo' => 'MB 1114', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '1986', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00021', 'cod_operacao' => 'OC01']);
        DB::table('equipamentos')->insert(['nome' => 'Pá Carregadeira Caterpillar 924F', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Caterpillar 924F', 'potencia' => '13', 'tipo_potencia' => '5', 'ano_fabricacao' => '1999', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00041', 'cod_operacao' => 'PC01']);
        DB::table('equipamentos')->insert(['nome' => 'Pá Carregadeira Case 721 C', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Case 721 C', 'potencia' => '16', 'tipo_potencia' => '5', 'ano_fabricacao' => '2005', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00061', 'cod_operacao' => 'PC02']);
        DB::table('equipamentos')->insert(['nome' => 'Caminhão Pipa MB 1519 6x2', 'descricao' => 'LYL-5491', 'marca_id' => '6', 'modelo' => 'MB 1519 6x2', 'potencia' => '12000', 'tipo_potencia' => '2', 'ano_fabricacao' => '1981', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00010', 'cod_operacao' => 'PP01']);
        DB::table('equipamentos')->insert(['nome' => 'Caminhão Pipa Ford 6x4 2425', 'descricao' => 'DBO-6156', 'marca_id' => '6', 'modelo' => 'Ford 6x4 2425', 'potencia' => '16000', 'tipo_potencia' => '2', 'ano_fabricacao' => '2000', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00023', 'cod_operacao' => 'PP02']);
        DB::table('equipamentos')->insert(['nome' => 'Rolo Compactador Tema Terra SPV84', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Tema Terra SPV84', 'potencia' => '12', 'tipo_potencia' => '5', 'ano_fabricacao' => '1994', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00045', 'cod_operacao' => 'RC01']);
        DB::table('equipamentos')->insert(['nome' => 'Rolo Compactador Dynapac CA 25 PD', 'descricao' => 'Pé de carneiro', 'marca_id' => '6', 'modelo' => 'Dynapac CA 25 PD', 'potencia' => '13', 'tipo_potencia' => '5', 'ano_fabricacao' => '1986', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00044', 'cod_operacao' => 'RC02']);
        DB::table('equipamentos')->insert(['nome' => 'Rolo Compactador Dynapac CA 25 PD', 'descricao' => 'Liso', 'marca_id' => '6', 'modelo' => 'Dynapac CA 25 PD', 'potencia' => '13', 'tipo_potencia' => '5', 'ano_fabricacao' => '1986', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00043', 'cod_operacao' => 'RC03']);
        DB::table('equipamentos')->insert(['nome' => 'Rolo Compactador Sany SY12CCA', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Sany SY12CCA', 'potencia' => '13', 'tipo_potencia' => '5', 'ano_fabricacao' => '2010', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00042', 'cod_operacao' => 'RC04']);
        DB::table('equipamentos')->insert(['nome' => 'Rolo Compactador Dinapac CC 1300', 'descricao' => 'Pneu', 'marca_id' => '6', 'modelo' => 'Dinapac CC 1300', 'potencia' => '4', 'tipo_potencia' => '5', 'ano_fabricacao' => '2022', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00084', 'cod_operacao' => 'RC05']);
        DB::table('equipamentos')->insert(['nome' => 'Rolo Compactador Tema Terra SP8000', 'descricao' => 'Pneu', 'marca_id' => '6', 'modelo' => 'Tema Terra SP8000', 'potencia' => '18', 'tipo_potencia' => '5', 'ano_fabricacao' => '1978', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00090', 'cod_operacao' => 'RC06']);
        DB::table('equipamentos')->insert(['nome' => 'Retroescavadeira Case 580M', 'descricao' => 'Maicon', 'marca_id' => '6', 'modelo' => 'Case 580M', 'potencia' => '8', 'tipo_potencia' => '5', 'ano_fabricacao' => '2011', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '90000', 'cod_operacao' => 'RE00']);
        DB::table('equipamentos')->insert(['nome' => 'Rompedor Hidráulico EDT 2000', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'EDT 2000', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2019', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00074', 'cod_operacao' => 'RH01']);
        DB::table('equipamentos')->insert(['nome' => 'Trator de Esteiras Fiatallis fd9', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Fiatallis fd9', 'potencia' => '13', 'tipo_potencia' => '5', 'ano_fabricacao' => '1989', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00051', 'cod_operacao' => 'TE01']);
        DB::table('equipamentos')->insert(['nome' => 'Trator de Esteiras John Deere', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'John Deere', 'potencia' => '15', 'tipo_potencia' => '5', 'ano_fabricacao' => '2017', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00050', 'cod_operacao' => 'TE02']);
        DB::table('equipamentos')->insert(['nome' => 'Trator de Esteiras Shantui SD 16', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Shantui SD 16', 'potencia' => '20', 'tipo_potencia' => '5', 'ano_fabricacao' => '2010', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00067', 'cod_operacao' => 'TE03']);
        DB::table('equipamentos')->insert(['nome' => 'Trator de Pneu CBT 8260 4x4', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'CBT 8260 4x4', 'potencia' => '6', 'tipo_potencia' => '5', 'ano_fabricacao' => '1986', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00053', 'cod_operacao' => 'TP01']);
        DB::table('equipamentos')->insert(['nome' => 'Usina Asfalto Cifali 40/60 PMF', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Cifali 40/60 PMF', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '1986', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00056', 'cod_operacao' => 'UA01']);
        //usina de asfalto já está cadastrado.
        //DB::table('equipamentos')->insert(['nome' => 'Usina Asfalto Cifali 60/80 CBUQ', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Cifali 60/80 CBUQ', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '1991', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00057', 'cod_operacao' => 'UA02']);
        DB::table('equipamentos')->insert(['nome' => 'Utilitário D20 - Cinza', 'descricao' => 'IEH-6059', 'marca_id' => '6', 'modelo' => 'D20 - Cinza', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '1996', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00031', 'cod_operacao' => 'UT01']);
        DB::table('equipamentos')->insert(['nome' => 'Utilitário D20 Veraneio', 'descricao' => 'LZO-3153', 'marca_id' => '6', 'modelo' => 'D20 Veraneio', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '1986', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00017', 'cod_operacao' => 'UT02']);
        DB::table('equipamentos')->insert(['nome' => 'Utilitário D20 - Azul', 'descricao' => 'GTA-0359', 'marca_id' => '6', 'modelo' => 'D20 - Azul', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '1994', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00032', 'cod_operacao' => 'UT03']);
        DB::table('equipamentos')->insert(['nome' => 'Utilitário Saveiro 1.6 CS', 'descricao' => 'MBA-2819', 'marca_id' => '6', 'modelo' => 'Saveiro 1.6 CS', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '1999', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00029', 'cod_operacao' => 'UT04']);
        DB::table('equipamentos')->insert(['nome' => 'Utilitário Saveiro 1.6 CE', 'descricao' => 'MLN-8975', 'marca_id' => '6', 'modelo' => 'Saveiro 1.6 CE', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2014', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00020', 'cod_operacao' => 'UT05']);
        DB::table('equipamentos')->insert(['nome' => 'Utilitário Hilux', 'descricao' => 'ITN-8903', 'marca_id' => '6', 'modelo' => 'Hilux', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2013', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00015', 'cod_operacao' => 'UT06']);
        DB::table('equipamentos')->insert(['nome' => 'Utilitário Strada Working', 'descricao' => 'RDY-8C52', 'marca_id' => '6', 'modelo' => 'Strada Working', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2020', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00013', 'cod_operacao' => 'UT07']);
        DB::table('equipamentos')->insert(['nome' => 'Vibro Acabadora Ciber AF4000', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Ciber AF4000', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2014', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00093', 'cod_operacao' => 'VA01']);
        DB::table('equipamentos')->insert(['nome' => 'Vassoura Mecânica Deltractor 1700', 'descricao' => '-', 'marca_id' => '6', 'modelo' => 'Deltractor 1700', 'potencia' => '0', 'tipo_potencia' => '0', 'ano_fabricacao' => '2022', 'controle_consumo' => '1', 'controle_saida' => '0', 'cod_fiscal' => '00076', 'cod_operacao' => 'VM01']); */
        DB::table('equipamentos')->insert(['nome' => 'KNAP & CIA', 'descricao' => 'EMPRESA DE DETONAÇÃO','marca_id'=>'6','controle_consumo' => '1', 'controle_saida' => '0']);
        DB::table('equipamentos')->insert(['nome' => 'NÃO IDENTIFICADO', 'descricao'=>'QUANDO NÃO SE SABE O NOME DO EQUIPAMENTO', 'marca_id'=>'6','controle_consumo' => '1', 'controle_saida' => '0']);
    }
}
