<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AddSaidaProduto extends Seeder
{
    /**
     * Run the ''database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade'=> '116', 'motivo'=> '1', 'data' => '2022-10-26', 'consumo_id' => '285']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade'=> '176', 'motivo'=> '1', 'data' => '2022-10-26', 'consumo_id' => '286']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade'=> '280', 'motivo'=> '1', 'data' => '2022-10-26', 'consumo_id' => '287']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade'=> '67', 'motivo'=> '1', 'data' => '2022-10-26', 'consumo_id' => '288']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade'=> '95', 'motivo'=> '1', 'data' => '2022-10-28', 'consumo_id' => '289']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade'=> '115', 'motivo'=> '1', 'data' => '2022-10-31', 'consumo_id' => '290']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade'=> '158', 'motivo'=> '1', 'data' => '2022-11-01', 'consumo_id' => '291']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade'=> '202', 'motivo'=> '1', 'data' => '2022-11-01', 'consumo_id' => '292']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade'=> '124', 'motivo'=> '1', 'data' => '2022-11-01', 'consumo_id' => '293']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '21', 'produto_id' => '2', 'quantidade'=> '101', 'motivo'=> '1', 'data' => '2022-11-03', 'consumo_id' => '294']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade'=> '134', 'motivo'=> '1', 'data' => '2022-11-04', 'consumo_id' => '295']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade'=> '84', 'motivo'=> '1', 'data' => '2022-11-04', 'consumo_id' => '296']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade'=> '117', 'motivo'=> '1', 'data' => '2022-11-05', 'consumo_id' => '297']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade'=> '103', 'motivo'=> '1', 'data' => '2022-11-08', 'consumo_id' => '298']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade'=> '264', 'motivo'=> '1', 'data' => '2022-11-08', 'consumo_id' => '299']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade'=> '131', 'motivo'=> '1', 'data' => '2022-11-09', 'consumo_id' => '300']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade'=> '88', 'motivo'=> '1', 'data' => '2022-11-12', 'consumo_id' => '301']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade'=> '55', 'motivo'=> '1', 'data' => '2022-11-12', 'consumo_id' => '302']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade'=> '113', 'motivo'=> '1', 'data' => '2022-11-14', 'consumo_id' => '303']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade'=> '400', 'motivo'=> '1', 'data' => '2022-11-15', 'consumo_id' => '304']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade'=> '120', 'motivo'=> '1', 'data' => '2022-11-16', 'consumo_id' => '305']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '62', 'motivo' => '1', 'data' => '2022-11-17', 'consumo_id' => '306']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '204', 'motivo' => '1', 'data' => '2022-11-19', 'consumo_id' => '307']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '152', 'motivo' => '1', 'data' => '2022-11-19', 'consumo_id' => '308']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '89', 'motivo' => '1', 'data' => '2022-11-21', 'consumo_id' => '309']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '119', 'motivo' => '1', 'data' => '2022-11-21', 'consumo_id' => '310']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '147', 'motivo' => '1', 'data' => '2022-11-23', 'consumo_id' => '311']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '97', 'motivo' => '1', 'data' => '2022-11-24', 'consumo_id' => '312']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '201', 'motivo' => '1', 'data' => '2022-11-26', 'consumo_id' => '313']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '116', 'motivo' => '1', 'data' => '2022-01-28', 'consumo_id' => '314']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '160', 'motivo' => '1', 'data' => '2022-11-30', 'consumo_id' => '315']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '126', 'motivo' => '1', 'data' => '2022-11-30', 'consumo_id' => '316']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '353', 'motivo' => '1', 'data' => '2022-12-01', 'consumo_id' => '317']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '115', 'motivo' => '1', 'data' => '2022-12-01', 'consumo_id' => '318']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '336', 'motivo' => '1', 'data' => '2022-12-06', 'consumo_id' => '319']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '132', 'motivo' => '1', 'data' => '2022-12-06', 'consumo_id' => '320']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '250', 'motivo' => '1', 'data' => '2022-12-08', 'consumo_id' => '321']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '21', 'produto_id' => '2', 'quantidade' => '252', 'motivo' => '1', 'data' => '2022-12-08', 'consumo_id' => '322']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '131', 'motivo' => '1', 'data' => '2022-12-10', 'consumo_id' => '323']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '148', 'motivo' => '1', 'data' => '2022-12-14', 'consumo_id' => '324']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '160', 'motivo' => '1', 'data' => '2022-12-20', 'consumo_id' => '325']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '154', 'motivo' => '1', 'data' => '2022-12-21', 'consumo_id' => '326']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '131', 'motivo' => '1', 'data' => '2022-12-22', 'consumo_id' => '327']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '100', 'motivo' => '1', 'data' => '2023-01-03', 'consumo_id' => '328']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '136', 'motivo' => '1', 'data' => '2023-01-03', 'consumo_id' => '329']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '150', 'motivo' => '1', 'data' => '2023-01-03', 'consumo_id' => '330']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '58', 'produto_id' => '2', 'quantidade' => '104', 'motivo' => '1', 'data' => '2023-01-04', 'consumo_id' => '331']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '127', 'motivo' => '1', 'data' => '2023-01-09', 'consumo_id' => '332']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '500', 'motivo' => '1', 'data' => '2023-01-11', 'consumo_id' => '333']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '132', 'motivo' => '1', 'data' => '2023-01-11', 'consumo_id' => '334']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '132', 'motivo' => '1', 'data' => '2023-01-16', 'consumo_id' => '335']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '521', 'motivo' => '1', 'data' => '2023-01-16', 'consumo_id' => '336']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '20', 'produto_id' => '2', 'quantidade' => '231', 'motivo' => '1', 'data' => '2023-01-20', 'consumo_id' => '337']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '133', 'motivo' => '1', 'data' => '2023-01-24', 'consumo_id' => '338']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '133', 'motivo' => '1', 'data' => '2023-01-26', 'consumo_id' => '339']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '73', 'motivo' => '1', 'data' => '2023-01-29', 'consumo_id' => '340']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '104', 'motivo' => '1', 'data' => '2023-01-31', 'consumo_id' => '341']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '90', 'motivo' => '1', 'data' => '2023-02-02', 'consumo_id' => '342']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '44', 'produto_id' => '2', 'quantidade' => '234', 'motivo' => '1', 'data' => '2023-02-03', 'consumo_id' => '343']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '117', 'motivo' => '1', 'data' => '2023-02-03', 'consumo_id' => '344']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '107', 'motivo' => '1', 'data' => '2023-02-04', 'consumo_id' => '345']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '200', 'motivo' => '1', 'data' => '2023-02-05', 'consumo_id' => '346']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '44', 'produto_id' => '2', 'quantidade' => '133', 'motivo' => '1', 'data' => '2023-02-06', 'consumo_id' => '347']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '97', 'motivo' => '1', 'data' => '2023-02-06', 'consumo_id' => '348']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '601', 'motivo' => '1', 'data' => '2023-02-06', 'consumo_id' => '349']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '44', 'produto_id' => '2', 'quantidade' => '144', 'motivo' => '1', 'data' => '2023-02-07', 'consumo_id' => '350']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '86', 'motivo' => '1', 'data' => '2023-02-07', 'consumo_id' => '351']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '54', 'motivo' => '1', 'data' => '2023-02-08', 'consumo_id' => '352']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '236', 'motivo' => '1', 'data' => '2023-02-08', 'consumo_id' => '353']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '401', 'motivo' => '1', 'data' => '2023-02-09', 'consumo_id' => '354']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '126', 'motivo' => '1', 'data' => '2023-02-09', 'consumo_id' => '355']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '108', 'motivo' => '1', 'data' => '2023-02-10', 'consumo_id' => '356']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '194', 'motivo' => '1', 'data' => '2023-02-10', 'consumo_id' => '357']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '64', 'produto_id' => '2', 'quantidade' => '200', 'motivo' => '1', 'data' => '2023-02-10', 'consumo_id' => '358']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '102', 'motivo' => '1', 'data' => '2023-02-13', 'consumo_id' => '359']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '193', 'motivo' => '1', 'data' => '2023-02-13', 'consumo_id' => '360']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '89', 'motivo' => '1', 'data' => '2023-02-13', 'consumo_id' => '361']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '401', 'motivo' => '1', 'data' => '2023-02-14', 'consumo_id' => '362']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '123', 'motivo' => '1', 'data' => '2023-02-14', 'consumo_id' => '363']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '199', 'motivo' => '1', 'data' => '2023-02-15', 'consumo_id' => '364']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '106', 'motivo' => '1', 'data' => '2023-02-15', 'consumo_id' => '365']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '104', 'motivo' => '1', 'data' => '2023-02-16', 'consumo_id' => '366']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '136', 'motivo' => '1', 'data' => '2023-02-16', 'consumo_id' => '367']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '200', 'motivo' => '1', 'data' => '2023-02-16', 'consumo_id' => '368']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '88', 'motivo' => '1', 'data' => '2023-02-17', 'consumo_id' => '369']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '201', 'motivo' => '1', 'data' => '2023-02-17', 'consumo_id' => '370']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '117', 'motivo' => '1', 'data' => '2023-02-17', 'consumo_id' => '371']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '110', 'motivo' => '1', 'data' => '2023-02-18', 'consumo_id' => '372']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '235', 'motivo' => '1', 'data' => '2023-02-18', 'consumo_id' => '373']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '141', 'motivo' => '1', 'data' => '2023-02-20', 'consumo_id' => '374']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '139', 'motivo' => '1', 'data' => '2023-02-21', 'consumo_id' => '375']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '261', 'motivo' => '1', 'data' => '2023-02-22', 'consumo_id' => '376']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '167', 'motivo' => '1', 'data' => '2023-02-22', 'consumo_id' => '377']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '201', 'motivo' => '1', 'data' => '2023-02-23', 'consumo_id' => '378']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '140', 'motivo' => '1', 'data' => '2023-02-23', 'consumo_id' => '379']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '143', 'motivo' => '1', 'data' => '2023-02-27', 'consumo_id' => '380']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '141', 'motivo' => '1', 'data' => '2023-02-28', 'consumo_id' => '381']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '286', 'motivo' => '1', 'data' => '2023-02-28', 'consumo_id' => '382']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '192', 'motivo' => '1', 'data' => '2023-03-01', 'consumo_id' => '383']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '157', 'motivo' => '1', 'data' => '2023-03-01', 'consumo_id' => '384']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '133', 'motivo' => '1', 'data' => '2023-03-02', 'consumo_id' => '385']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '101', 'motivo' => '1', 'data' => '2023-03-03', 'consumo_id' => '386']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '223', 'motivo' => '1', 'data' => '2023-03-03', 'consumo_id' => '387']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '127', 'motivo' => '1', 'data' => '2023-05-06', 'consumo_id' => '388']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '118', 'motivo' => '1', 'data' => '2023-03-06', 'consumo_id' => '389']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '185', 'motivo' => '1', 'data' => '2023-03-06', 'consumo_id' => '390']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '116', 'motivo' => '1', 'data' => '2023-03-08', 'consumo_id' => '391']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '201', 'motivo' => '1', 'data' => '2023-03-09', 'consumo_id' => '392']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '182', 'motivo' => '1', 'data' => '2023-03-13', 'consumo_id' => '393']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '126', 'motivo' => '1', 'data' => '2023-03-13', 'consumo_id' => '394']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '129', 'motivo' => '1', 'data' => '2023-03-13', 'consumo_id' => '395']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '229', 'motivo' => '1', 'data' => '2023-03-15', 'consumo_id' => '396']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '114', 'motivo' => '1', 'data' => '2023-03-15', 'consumo_id' => '397']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '116', 'motivo' => '1', 'data' => '2023-03-17', 'consumo_id' => '398']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '233', 'motivo' => '1', 'data' => '2023-03-17', 'consumo_id' => '399']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '100', 'motivo' => '1', 'data' => '2023-03-17', 'consumo_id' => '400']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '46', 'produto_id' => '2', 'quantidade' => '362', 'motivo' => '1', 'data' => '2023-03-20', 'consumo_id' => '401']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '27', 'produto_id' => '2', 'quantidade' => '237', 'motivo' => '1', 'data' => '2023-03-20', 'consumo_id' => '402']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '114', 'motivo' => '1', 'data' => '2023-03-20', 'consumo_id' => '403']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '46', 'produto_id' => '2', 'quantidade' => '273', 'motivo' => '1', 'data' => '2023-03-22', 'consumo_id' => '404']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '206', 'motivo' => '1', 'data' => '2023-03-22', 'consumo_id' => '405']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '137', 'motivo' => '1', 'data' => '2023-03-23', 'consumo_id' => '406']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '51', 'produto_id' => '2', 'quantidade' => '300', 'motivo' => '1', 'data' => '2023-03-23', 'consumo_id' => '407']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '51', 'produto_id' => '2', 'quantidade' => '357', 'motivo' => '1', 'data' => '2023-03-24', 'consumo_id' => '408']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '149', 'motivo' => '1', 'data' => '2023-03-27', 'consumo_id' => '409']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '47', 'produto_id' => '2', 'quantidade' => '120', 'motivo' => '1', 'data' => '2023-03-29', 'consumo_id' => '410']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '105', 'motivo' => '1', 'data' => '2023-03-31', 'consumo_id' => '411']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '124', 'motivo' => '1', 'data' => '2023-04-08', 'consumo_id' => '412']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '46', 'produto_id' => '2', 'quantidade' => '358', 'motivo' => '1', 'data' => '2023-04-10', 'consumo_id' => '413']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '143', 'motivo' => '1', 'data' => '2023-04-11', 'consumo_id' => '414']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '136', 'motivo' => '1', 'data' => '2023-04-12', 'consumo_id' => '415']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '115', 'motivo' => '1', 'data' => '2023-04-15', 'consumo_id' => '416']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '112', 'motivo' => '1', 'data' => '2023-04-15', 'consumo_id' => '417']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '258', 'motivo' => '1', 'data' => '2023-04-17', 'consumo_id' => '418']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '152', 'motivo' => '1', 'data' => '2023-04-17', 'consumo_id' => '419']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '104', 'motivo' => '1', 'data' => '2023-04-17', 'consumo_id' => '420']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '695', 'motivo' => '1', 'data' => '2023-04-18', 'consumo_id' => '421']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '266', 'motivo' => '1', 'data' => '2023-04-19', 'consumo_id' => '422']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '85', 'motivo' => '1', 'data' => '2023-04-19', 'consumo_id' => '423']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '71', 'motivo' => '1', 'data' => '2023-04-20', 'consumo_id' => '424']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '65', 'motivo' => '1', 'data' => '2023-04-21', 'consumo_id' => '425']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '149', 'motivo' => '1', 'data' => '2023-04-22', 'consumo_id' => '426']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '279', 'motivo' => '1', 'data' => '2023-04-22', 'consumo_id' => '427']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '103', 'motivo' => '1', 'data' => '2023-04-25', 'consumo_id' => '428']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '286', 'motivo' => '1', 'data' => '2023-04-26', 'consumo_id' => '429']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '12', 'motivo' => '1', 'data' => '2023-04-26', 'consumo_id' => '430']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '161', 'motivo' => '1', 'data' => '2023-04-27', 'consumo_id' => '431']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '88', 'produto_id' => '2', 'quantidade' => '90', 'motivo' => '1', 'data' => '2023-04-27', 'consumo_id' => '460']);

        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '275', 'motivo' => '1', 'data' => '2023-04-28', 'consumo_id' => '432']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '124', 'motivo' => '1', 'data' => '2023-04-29', 'consumo_id' => '433']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '360', 'motivo' => '1', 'data' => '2023-05-02', 'consumo_id' => '434']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '71', 'motivo' => '1', 'data' => '2023-05-03', 'consumo_id' => '435']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '360', 'motivo' => '1', 'data' => '2023-05-03', 'consumo_id' => '436']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '256', 'motivo' => '1', 'data' => '2023-05-03', 'consumo_id' => '437']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '103', 'motivo' => '1', 'data' => '2023-05-08', 'consumo_id' => '438']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '128', 'motivo' => '1', 'data' => '2023-05-08', 'consumo_id' => '439']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '76', 'motivo' => '1', 'data' => '2023-05-10', 'consumo_id' => '440']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '88', 'produto_id' => '2', 'quantidade' => '202', 'motivo' => '1', 'data' => '2023-07-02', 'consumo_id' => '441']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '296', 'motivo' => '1', 'data' => '2023-05-10', 'consumo_id' => '442']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '20', 'produto_id' => '2', 'quantidade' => '204', 'motivo' => '1', 'data' => '2023-05-11', 'consumo_id' => '443']);
       
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '146', 'motivo' => '1', 'data' => '2023-05-12', 'consumo_id' => '444']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '252', 'motivo' => '1', 'data' => '2023-05-13', 'consumo_id' => '445']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '126', 'motivo' => '1', 'data' => '2023-05-15', 'consumo_id' => '446']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '43', 'produto_id' => '2', 'quantidade' => '118', 'motivo' => '1', 'data' => '2023-05-15', 'consumo_id' => '447']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '242', 'motivo' => '1', 'data' => '2023-05-16', 'consumo_id' => '448']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '43', 'produto_id' => '2', 'quantidade' => '100', 'motivo' => '1', 'data' => '2023-05-16', 'consumo_id' => '449']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '142', 'motivo' => '1', 'data' => '2023-05-18', 'consumo_id' => '450']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '43', 'produto_id' => '2', 'quantidade' => '126', 'motivo' => '1', 'data' => '2023-05-18', 'consumo_id' => '451']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '10', 'motivo' => '1', 'data' => '2023-05-18', 'consumo_id' => '452']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '43', 'produto_id' => '2', 'quantidade' => '252', 'motivo' => '1', 'data' => '2023-05-22', 'consumo_id' => '453']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '156', 'motivo' => '1', 'data' => '2023-05-23', 'consumo_id' => '454']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '608', 'motivo' => '1', 'data' => '2023-05-24', 'consumo_id' => '455']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '71', 'motivo' => '1', 'data' => '2023-05-24', 'consumo_id' => '456']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '4', 'motivo' => '1', 'data' => '2023-05-25', 'consumo_id' => '457']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '141', 'motivo' => '1', 'data' => '2023-06-25', 'consumo_id' => '458']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '160', 'motivo' => '1', 'data' => '2023-05-26', 'consumo_id' => '459']);
    }
}
