<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AddSaidaProduto extends Seeder
{
    /**
     * Run the ''database seeds.
     *
     * @return void
     */
    /*  public function run()
    {
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade'=> '116', 'motivo'=> '1', 'data' => '2022-10-26']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade'=> '176', 'motivo'=> '1', 'data' => '2022-10-26']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade'=> '280', 'motivo'=> '1', 'data' => '2022-10-26']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade'=> '67', 'motivo'=> '1', 'data' => '2022-10-26']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade'=> '95', 'motivo'=> '1', 'data' => '2022-10-28']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade'=> '115', 'motivo'=> '1', 'data' => '2022-10-31']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade'=> '158', 'motivo'=> '1', 'data' => '2022-11-01']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade'=> '202', 'motivo'=> '1', 'data' => '2022-11-01']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade'=> '124', 'motivo'=> '1', 'data' => '2022-11-01']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '21', 'produto_id' => '2', 'quantidade'=> '101', 'motivo'=> '1', 'data' => '2022-11-03']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade'=> '134', 'motivo'=> '1', 'data' => '2022-11-04']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade'=> '84', 'motivo'=> '1', 'data' => '2022-11-04']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade'=> '117', 'motivo'=> '1', 'data' => '2022-11-05']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade'=> '103', 'motivo'=> '1', 'data' => '2022-11-08']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade'=> '264', 'motivo'=> '1', 'data' => '2022-11-08']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade'=> '131', 'motivo'=> '1', 'data' => '2022-11-09']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade'=> '88', 'motivo'=> '1', 'data' => '2022-11-12']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade'=> '55', 'motivo'=> '1', 'data' => '2022-11-12']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade'=> '113', 'motivo'=> '1', 'data' => '2022-11-14']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade'=> '400', 'motivo'=> '1', 'data' => '2022-11-15']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade'=> '120', 'motivo'=> '1', 'data' => '2022-11-16']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '62', 'motivo' => '1', 'data' => '2022-11-17']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '204', 'motivo' => '1', 'data' => '2022-11-19']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '152', 'motivo' => '1', 'data' => '2022-11-19']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '89', 'motivo' => '1', 'data' => '2022-11-21']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '119', 'motivo' => '1', 'data' => '2022-11-21']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '147', 'motivo' => '1', 'data' => '2022-11-23']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '97', 'motivo' => '1', 'data' => '2022-11-24']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '201', 'motivo' => '1', 'data' => '2022-11-26']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '116', 'motivo' => '1', 'data' => '2022-01-28']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '160', 'motivo' => '1', 'data' => '2022-11-30']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '126', 'motivo' => '1', 'data' => '2022-11-30']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '353', 'motivo' => '1', 'data' => '2022-12-01']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '115', 'motivo' => '1', 'data' => '2022-12-01']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '336', 'motivo' => '1', 'data' => '2022-12-06']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '132', 'motivo' => '1', 'data' => '2022-12-06']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '250', 'motivo' => '1', 'data' => '2022-12-08']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '21', 'produto_id' => '2', 'quantidade' => '252', 'motivo' => '1', 'data' => '2022-12-08']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '131', 'motivo' => '1', 'data' => '2022-12-10']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '148', 'motivo' => '1', 'data' => '2022-12-14']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '160', 'motivo' => '1', 'data' => '2022-12-20']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '154', 'motivo' => '1', 'data' => '2022-12-21']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '131', 'motivo' => '1', 'data' => '2022-12-22']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '100', 'motivo' => '1', 'data' => '2023-01-03']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '136', 'motivo' => '1', 'data' => '2023-01-03']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '150', 'motivo' => '1', 'data' => '2023-01-03']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '58', 'produto_id' => '2', 'quantidade' => '104', 'motivo' => '1', 'data' => '2023-01-04']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '127', 'motivo' => '1', 'data' => '2023-01-09']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '500', 'motivo' => '1', 'data' => '2023-01-11']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '132', 'motivo' => '1', 'data' => '2023-01-11']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '132', 'motivo' => '1', 'data' => '2023-01-16']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '521', 'motivo' => '1', 'data' => '2023-01-16']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '20', 'produto_id' => '2', 'quantidade' => '231', 'motivo' => '1', 'data' => '2023-01-20']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '133', 'motivo' => '1', 'data' => '2023-01-24']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '133', 'motivo' => '1', 'data' => '2023-01-26']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '73', 'motivo' => '1', 'data' => '2023-01-29']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '104', 'motivo' => '1', 'data' => '2023-01-31']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '90', 'motivo' => '1', 'data' => '2023-02-02']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '44', 'produto_id' => '2', 'quantidade' => '234', 'motivo' => '1', 'data' => '2023-02-03']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '117', 'motivo' => '1', 'data' => '2023-02-03']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '107', 'motivo' => '1', 'data' => '2023-02-04']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '200', 'motivo' => '1', 'data' => '2023-02-05']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '44', 'produto_id' => '2', 'quantidade' => '133', 'motivo' => '1', 'data' => '2023-02-06']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '97', 'motivo' => '1', 'data' => '2023-02-06']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '601', 'motivo' => '1', 'data' => '2023-02-06']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '44', 'produto_id' => '2', 'quantidade' => '144', 'motivo' => '1', 'data' => '2023-02-07']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '86', 'motivo' => '1', 'data' => '2023-02-07']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '54', 'motivo' => '1', 'data' => '2023-02-08']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '236', 'motivo' => '1', 'data' => '2023-02-08']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '401', 'motivo' => '1', 'data' => '2023-02-09']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '126', 'motivo' => '1', 'data' => '2023-02-09']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '108', 'motivo' => '1', 'data' => '2023-02-10']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '194', 'motivo' => '1', 'data' => '2023-02-10']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '64', 'produto_id' => '2', 'quantidade' => '200', 'motivo' => '1', 'data' => '2023-02-10']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '102', 'motivo' => '1', 'data' => '2023-02-13']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '193', 'motivo' => '1', 'data' => '2023-02-13']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '89', 'motivo' => '1', 'data' => '2023-02-13']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '401', 'motivo' => '1', 'data' => '2023-02-14']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '123', 'motivo' => '1', 'data' => '2023-02-14']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '199', 'motivo' => '1', 'data' => '2023-02-15']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '106', 'motivo' => '1', 'data' => '2023-02-15']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '104', 'motivo' => '1', 'data' => '2023-02-16']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '136', 'motivo' => '1', 'data' => '2023-02-16']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '200', 'motivo' => '1', 'data' => '2023-02-16']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '88', 'motivo' => '1', 'data' => '2023-02-17']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '201', 'motivo' => '1', 'data' => '2023-02-17']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '117', 'motivo' => '1', 'data' => '2023-02-17']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '110', 'motivo' => '1', 'data' => '2023-02-18']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '235', 'motivo' => '1', 'data' => '2023-02-18']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '141', 'motivo' => '1', 'data' => '2023-02-20']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '139', 'motivo' => '1', 'data' => '2023-02-21']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '261', 'motivo' => '1', 'data' => '2023-02-22']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '167', 'motivo' => '1', 'data' => '2023-02-22']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '201', 'motivo' => '1', 'data' => '2023-02-23']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '140', 'motivo' => '1', 'data' => '2023-02-23']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '143', 'motivo' => '1', 'data' => '2023-02-27']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '141', 'motivo' => '1', 'data' => '2023-02-28']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '286', 'motivo' => '1', 'data' => '2023-02-28']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '192', 'motivo' => '1', 'data' => '2023-03-01']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '157', 'motivo' => '1', 'data' => '2023-03-01']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '133', 'motivo' => '1', 'data' => '2023-03-02']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '101', 'motivo' => '1', 'data' => '2023-03-03']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '223', 'motivo' => '1', 'data' => '2023-03-03']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '127', 'motivo' => '1', 'data' => '2023-05-06']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '118', 'motivo' => '1', 'data' => '2023-03-06']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '185', 'motivo' => '1', 'data' => '2023-03-06']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '116', 'motivo' => '1', 'data' => '2023-03-08']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '201', 'motivo' => '1', 'data' => '2023-03-09']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '182', 'motivo' => '1', 'data' => '2023-03-13']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '126', 'motivo' => '1', 'data' => '2023-03-13']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '129', 'motivo' => '1', 'data' => '2023-03-13']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '229', 'motivo' => '1', 'data' => '2023-03-15']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '114', 'motivo' => '1', 'data' => '2023-03-15']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '116', 'motivo' => '1', 'data' => '2023-03-17']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '233', 'motivo' => '1', 'data' => '2023-03-17']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '100', 'motivo' => '1', 'data' => '2023-03-17']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '46', 'produto_id' => '2', 'quantidade' => '362', 'motivo' => '1', 'data' => '2023-03-20']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '27', 'produto_id' => '2', 'quantidade' => '237', 'motivo' => '1', 'data' => '2023-03-20']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '114', 'motivo' => '1', 'data' => '2023-03-20']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '46', 'produto_id' => '2', 'quantidade' => '273', 'motivo' => '1', 'data' => '2023-03-22']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '206', 'motivo' => '1', 'data' => '2023-03-22']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '137', 'motivo' => '1', 'data' => '2023-03-23']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '51', 'produto_id' => '2', 'quantidade' => '300', 'motivo' => '1', 'data' => '2023-03-23']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '51', 'produto_id' => '2', 'quantidade' => '357', 'motivo' => '1', 'data' => '2023-03-24']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '149', 'motivo' => '1', 'data' => '2023-03-27']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '47', 'produto_id' => '2', 'quantidade' => '120', 'motivo' => '1', 'data' => '2023-03-29']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '105', 'motivo' => '1', 'data' => '2023-03-31']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '124', 'motivo' => '1', 'data' => '2023-04-08']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '46', 'produto_id' => '2', 'quantidade' => '358', 'motivo' => '1', 'data' => '2023-04-10']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '143', 'motivo' => '1', 'data' => '2023-04-11']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '136', 'motivo' => '1', 'data' => '2023-04-12']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '115', 'motivo' => '1', 'data' => '2023-04-15']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '112', 'motivo' => '1', 'data' => '2023-04-15']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '258', 'motivo' => '1', 'data' => '2023-04-17']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '152', 'motivo' => '1', 'data' => '2023-04-17']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '104', 'motivo' => '1', 'data' => '2023-04-17']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '695', 'motivo' => '1', 'data' => '2023-04-18']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '266', 'motivo' => '1', 'data' => '2023-04-19']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '85', 'motivo' => '1', 'data' => '2023-04-19']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '71', 'motivo' => '1', 'data' => '2023-04-20']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '65', 'motivo' => '1', 'data' => '2023-04-21']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '149', 'motivo' => '1', 'data' => '2023-04-22']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '279', 'motivo' => '1', 'data' => '2023-04-22']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '103', 'motivo' => '1', 'data' => '2023-04-25']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '286', 'motivo' => '1', 'data' => '2023-04-26']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '12', 'motivo' => '1', 'data' => '2023-04-26']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '161', 'motivo' => '1', 'data' => '2023-04-27']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '88', 'produto_id' => '2', 'quantidade' => '90', 'motivo' => '1', 'data' => '2023-04-27']);

        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '275', 'motivo' => '1', 'data' => '2023-04-28']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '124', 'motivo' => '1', 'data' => '2023-04-29']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '360', 'motivo' => '1', 'data' => '2023-05-02']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '71', 'motivo' => '1', 'data' => '2023-05-03']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '360', 'motivo' => '1', 'data' => '2023-05-03']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '256', 'motivo' => '1', 'data' => '2023-05-03']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '103', 'motivo' => '1', 'data' => '2023-05-08']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '128', 'motivo' => '1', 'data' => '2023-05-08']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '76', 'motivo' => '1', 'data' => '2023-05-10']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '88', 'produto_id' => '2', 'quantidade' => '202', 'motivo' => '1', 'data' => '2023-05-02']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '296', 'motivo' => '1', 'data' => '2023-05-10']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '20', 'produto_id' => '2', 'quantidade' => '204', 'motivo' => '1', 'data' => '2023-05-11']);
       
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '146', 'motivo' => '1', 'data' => '2023-05-12']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '252', 'motivo' => '1', 'data' => '2023-05-13']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '126', 'motivo' => '1', 'data' => '2023-05-15']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '43', 'produto_id' => '2', 'quantidade' => '118', 'motivo' => '1', 'data' => '2023-05-15']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '242', 'motivo' => '1', 'data' => '2023-05-16']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '43', 'produto_id' => '2', 'quantidade' => '100', 'motivo' => '1', 'data' => '2023-05-16']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '142', 'motivo' => '1', 'data' => '2023-05-18']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '43', 'produto_id' => '2', 'quantidade' => '126', 'motivo' => '1', 'data' => '2023-05-18']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '10', 'motivo' => '1', 'data' => '2023-05-18']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '43', 'produto_id' => '2', 'quantidade' => '252', 'motivo' => '1', 'data' => '2023-05-22']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '156', 'motivo' => '1', 'data' => '2023-05-23']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '608', 'motivo' => '1', 'data' => '2023-05-24']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '71', 'motivo' => '1', 'data' => '2023-05-24']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '4', 'motivo' => '1', 'data' => '2023-05-25']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '141', 'motivo' => '1', 'data' => '2023-05-25']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '160', 'motivo' => '1', 'data' => '2023-05-26']);
    } */

    public function run()
    {
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '116','motivo'=>'1', 'data' => '2022-10-26', 'abastecimento_id' => '18']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '176','motivo'=>'1', 'data' => '2022-10-26', 'abastecimento_id' => '19']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '280','motivo'=>'1', 'data' => '2022-10-26', 'abastecimento_id' => '20']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '67','motivo'=>'1', 'data' => '2022-10-26', 'abastecimento_id' => '21']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '95','motivo'=>'1', 'data' => '2022-10-28', 'abastecimento_id' => '22']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '115','motivo'=>'1', 'data' => '2022-10-31', 'abastecimento_id' => '23']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '158','motivo'=>'1', 'data' => '2022-11-01', 'abastecimento_id' => '24']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '202','motivo'=>'1', 'data' => '2022-11-01', 'abastecimento_id' => '25']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '124','motivo'=>'1', 'data' => '2022-11-01', 'abastecimento_id' => '26']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '21', 'produto_id' => '2', 'quantidade' => '101','motivo'=>'1', 'data' => '2022-11-03', 'abastecimento_id' => '27']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '134','motivo'=>'1', 'data' => '2022-11-04', 'abastecimento_id' => '28']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '84','motivo'=>'1', 'data' => '2022-11-04', 'abastecimento_id' => '29']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '117','motivo'=>'1', 'data' => '2022-11-05', 'abastecimento_id' => '30']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '103','motivo'=>'1', 'data' => '2022-11-08', 'abastecimento_id' => '31']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '264','motivo'=>'1', 'data' => '2022-11-08', 'abastecimento_id' => '32']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '131','motivo'=>'1', 'data' => '2022-11-09', 'abastecimento_id' => '33']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '88','motivo'=>'1', 'data' => '2022-11-12', 'abastecimento_id' => '34']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '55','motivo'=>'1', 'data' => '2022-11-12', 'abastecimento_id' => '35']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '113','motivo'=>'1', 'data' => '2022-11-14', 'abastecimento_id' => '36']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '400','motivo'=>'1', 'data' => '2022-11-15', 'abastecimento_id' => '37']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '120','motivo'=>'1', 'data' => '2022-11-16', 'abastecimento_id' => '38']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '62','motivo'=>'1', 'data' => '2022-11-17', 'abastecimento_id' => '39']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '204','motivo'=>'1', 'data' => '2022-11-19', 'abastecimento_id' => '40']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '152','motivo'=>'1', 'data' => '2022-11-19', 'abastecimento_id' => '41']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '89','motivo'=>'1', 'data' => '2022-11-21', 'abastecimento_id' => '42']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '119','motivo'=>'1', 'data' => '2022-11-21', 'abastecimento_id' => '43']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '147','motivo'=>'1', 'data' => '2022-11-23', 'abastecimento_id' => '44']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '97','motivo'=>'1', 'data' => '2022-11-24', 'abastecimento_id' => '45']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '201','motivo'=>'1', 'data' => '2022-11-26', 'abastecimento_id' => '46']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '116','motivo'=>'1', 'data' => '2022-01-28', 'abastecimento_id' => '47']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '160','motivo'=>'1', 'data' => '2022-11-30', 'abastecimento_id' => '48']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '126','motivo'=>'1', 'data' => '2022-11-30', 'abastecimento_id' => '49']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '353','motivo'=>'1', 'data' => '2022-12-01', 'abastecimento_id' => '50']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '115','motivo'=>'1', 'data' => '2022-12-01', 'abastecimento_id' => '51']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '336','motivo'=>'1', 'data' => '2022-12-06', 'abastecimento_id' => '52']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '132','motivo'=>'1', 'data' => '2022-12-06', 'abastecimento_id' => '53']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '250','motivo'=>'1', 'data' => '2022-12-08', 'abastecimento_id' => '54']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '21', 'produto_id' => '2', 'quantidade' => '252','motivo'=>'1', 'data' => '2022-12-08', 'abastecimento_id' => '55']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '131','motivo'=>'1', 'data' => '2022-12-10', 'abastecimento_id' => '56']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '148','motivo'=>'1', 'data' => '2022-12-14', 'abastecimento_id' => '57']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '160','motivo'=>'1', 'data' => '2022-12-20', 'abastecimento_id' => '58']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '154','motivo'=>'1', 'data' => '2022-12-21', 'abastecimento_id' => '59']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '131','motivo'=>'1', 'data' => '2022-12-22', 'abastecimento_id' => '60']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '100','motivo'=>'1', 'data' => '2023-01-03', 'abastecimento_id' => '61']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '136','motivo'=>'1', 'data' => '2023-01-03', 'abastecimento_id' => '62']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '150','motivo'=>'1', 'data' => '2023-01-03', 'abastecimento_id' => '63']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '58', 'produto_id' => '2', 'quantidade' => '104','motivo'=>'1', 'data' => '2023-01-04', 'abastecimento_id' => '64']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '127','motivo'=>'1', 'data' => '2023-01-09', 'abastecimento_id' => '65']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '500','motivo'=>'1', 'data' => '2023-01-11', 'abastecimento_id' => '66']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '132','motivo'=>'1', 'data' => '2023-01-11', 'abastecimento_id' => '67']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '132','motivo'=>'1', 'data' => '2023-01-16', 'abastecimento_id' => '68']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '521','motivo'=>'1', 'data' => '2023-01-16', 'abastecimento_id' => '69']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '20', 'produto_id' => '2', 'quantidade' => '231','motivo'=>'1', 'data' => '2023-01-20', 'abastecimento_id' => '70']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '133','motivo'=>'1', 'data' => '2023-01-24', 'abastecimento_id' => '71']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '133','motivo'=>'1', 'data' => '2023-01-26', 'abastecimento_id' => '72']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '73','motivo'=>'1', 'data' => '2023-01-29', 'abastecimento_id' => '73']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '104','motivo'=>'1', 'data' => '2023-01-31', 'abastecimento_id' => '74']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '90','motivo'=>'1', 'data' => '2023-02-02', 'abastecimento_id' => '75']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '44', 'produto_id' => '2', 'quantidade' => '234','motivo'=>'1', 'data' => '2023-02-03', 'abastecimento_id' => '76']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '117','motivo'=>'1', 'data' => '2023-02-03', 'abastecimento_id' => '77']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '107','motivo'=>'1', 'data' => '2023-02-04', 'abastecimento_id' => '78']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '200','motivo'=>'1', 'data' => '2023-02-05', 'abastecimento_id' => '79']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '44', 'produto_id' => '2', 'quantidade' => '133','motivo'=>'1', 'data' => '2023-02-06', 'abastecimento_id' => '80']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '97','motivo'=>'1', 'data' => '2023-02-06', 'abastecimento_id' => '81']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '601','motivo'=>'1', 'data' => '2023-02-06', 'abastecimento_id' => '82']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '44', 'produto_id' => '2', 'quantidade' => '144','motivo'=>'1', 'data' => '2023-02-07', 'abastecimento_id' => '83']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '86','motivo'=>'1', 'data' => '2023-02-07', 'abastecimento_id' => '84']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '54','motivo'=>'1', 'data' => '2023-02-08', 'abastecimento_id' => '85']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '236','motivo'=>'1', 'data' => '2023-02-08', 'abastecimento_id' => '86']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '401','motivo'=>'1', 'data' => '2023-02-09', 'abastecimento_id' => '87']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '126','motivo'=>'1', 'data' => '2023-02-09', 'abastecimento_id' => '88']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '108','motivo'=>'1', 'data' => '2023-02-10', 'abastecimento_id' => '89']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '194','motivo'=>'1', 'data' => '2023-02-10', 'abastecimento_id' => '90']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '64', 'produto_id' => '2', 'quantidade' => '200','motivo'=>'1', 'data' => '2023-02-10', 'abastecimento_id' => '91']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '102','motivo'=>'1', 'data' => '2023-02-13', 'abastecimento_id' => '92']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '193','motivo'=>'1', 'data' => '2023-02-13', 'abastecimento_id' => '93']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '89','motivo'=>'1', 'data' => '2023-02-13', 'abastecimento_id' => '94']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '401','motivo'=>'1', 'data' => '2023-02-14', 'abastecimento_id' => '95']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '123','motivo'=>'1', 'data' => '2023-02-14', 'abastecimento_id' => '96']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '199','motivo'=>'1', 'data' => '2023-02-15', 'abastecimento_id' => '97']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '106','motivo'=>'1', 'data' => '2023-02-15', 'abastecimento_id' => '98']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '104','motivo'=>'1', 'data' => '2023-02-16', 'abastecimento_id' => '99']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '136','motivo'=>'1', 'data' => '2023-02-16', 'abastecimento_id' => '100']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '200','motivo'=>'1', 'data' => '2023-02-16', 'abastecimento_id' => '101']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '88','motivo'=>'1', 'data' => '2023-02-17', 'abastecimento_id' => '102']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '201','motivo'=>'1', 'data' => '2023-02-17', 'abastecimento_id' => '103']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '117','motivo'=>'1', 'data' => '2023-02-17', 'abastecimento_id' => '104']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '110','motivo'=>'1', 'data' => '2023-02-18', 'abastecimento_id' => '105']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '235','motivo'=>'1', 'data' => '2023-02-18', 'abastecimento_id' => '106']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '141','motivo'=>'1', 'data' => '2023-02-20', 'abastecimento_id' => '107']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '139','motivo'=>'1', 'data' => '2023-02-21', 'abastecimento_id' => '108']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '261','motivo'=>'1', 'data' => '2023-02-22', 'abastecimento_id' => '109']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '167','motivo'=>'1', 'data' => '2023-02-22', 'abastecimento_id' => '110']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '201','motivo'=>'1', 'data' => '2023-02-23', 'abastecimento_id' => '111']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '140','motivo'=>'1', 'data' => '2023-02-23', 'abastecimento_id' => '112']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '143','motivo'=>'1', 'data' => '2023-02-27', 'abastecimento_id' => '113']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '141','motivo'=>'1', 'data' => '2023-02-28', 'abastecimento_id' => '114']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '286','motivo'=>'1', 'data' => '2023-02-28', 'abastecimento_id' => '115']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '192','motivo'=>'1', 'data' => '2023-03-01', 'abastecimento_id' => '116']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '157','motivo'=>'1', 'data' => '2023-03-01', 'abastecimento_id' => '117']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '133','motivo'=>'1', 'data' => '2023-03-02', 'abastecimento_id' => '118']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '101','motivo'=>'1', 'data' => '2023-03-03', 'abastecimento_id' => '119']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '223','motivo'=>'1', 'data' => '2023-03-03', 'abastecimento_id' => '120']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '127','motivo'=>'1', 'data' => '2023-05-06', 'abastecimento_id' => '121']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '118','motivo'=>'1', 'data' => '2023-03-06', 'abastecimento_id' => '122']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '185','motivo'=>'1', 'data' => '2023-03-06', 'abastecimento_id' => '123']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '116','motivo'=>'1', 'data' => '2023-03-08', 'abastecimento_id' => '124']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '201','motivo'=>'1', 'data' => '2023-03-09', 'abastecimento_id' => '125']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '182','motivo'=>'1', 'data' => '2023-03-13', 'abastecimento_id' => '126']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '126','motivo'=>'1', 'data' => '2023-03-13', 'abastecimento_id' => '127']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '129','motivo'=>'1', 'data' => '2023-03-13', 'abastecimento_id' => '128']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '229','motivo'=>'1', 'data' => '2023-03-15', 'abastecimento_id' => '129']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '18', 'produto_id' => '2', 'quantidade' => '114','motivo'=>'1', 'data' => '2023-03-15', 'abastecimento_id' => '130']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '116','motivo'=>'1', 'data' => '2023-03-17', 'abastecimento_id' => '131']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '233','motivo'=>'1', 'data' => '2023-03-17', 'abastecimento_id' => '132']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '100','motivo'=>'1', 'data' => '2023-03-17', 'abastecimento_id' => '133']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '46', 'produto_id' => '2', 'quantidade' => '362','motivo'=>'1', 'data' => '2023-03-20', 'abastecimento_id' => '134']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '27', 'produto_id' => '2', 'quantidade' => '237','motivo'=>'1', 'data' => '2023-03-20', 'abastecimento_id' => '135']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '114','motivo'=>'1', 'data' => '2023-03-20', 'abastecimento_id' => '136']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '46', 'produto_id' => '2', 'quantidade' => '273','motivo'=>'1', 'data' => '2023-03-22', 'abastecimento_id' => '137']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '206','motivo'=>'1', 'data' => '2023-03-22', 'abastecimento_id' => '138']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '137','motivo'=>'1', 'data' => '2023-03-23', 'abastecimento_id' => '139']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '51', 'produto_id' => '2', 'quantidade' => '300','motivo'=>'1', 'data' => '2023-03-23', 'abastecimento_id' => '140']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '51', 'produto_id' => '2', 'quantidade' => '357','motivo'=>'1', 'data' => '2023-03-24', 'abastecimento_id' => '141']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '149','motivo'=>'1', 'data' => '2023-03-27', 'abastecimento_id' => '142']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '47', 'produto_id' => '2', 'quantidade' => '120','motivo'=>'1', 'data' => '2023-03-29', 'abastecimento_id' => '143']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '105','motivo'=>'1', 'data' => '2023-03-31', 'abastecimento_id' => '144']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '124','motivo'=>'1', 'data' => '2023-04-08', 'abastecimento_id' => '145']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '46', 'produto_id' => '2', 'quantidade' => '358','motivo'=>'1', 'data' => '2023-04-10', 'abastecimento_id' => '146']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '143','motivo'=>'1', 'data' => '2023-04-11', 'abastecimento_id' => '147']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '136','motivo'=>'1', 'data' => '2023-04-12', 'abastecimento_id' => '148']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '115','motivo'=>'1', 'data' => '2023-04-15', 'abastecimento_id' => '149']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '112','motivo'=>'1', 'data' => '2023-04-15', 'abastecimento_id' => '150']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '258','motivo'=>'1', 'data' => '2023-04-17', 'abastecimento_id' => '151']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '152','motivo'=>'1', 'data' => '2023-04-17', 'abastecimento_id' => '152']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '104','motivo'=>'1', 'data' => '2023-04-17', 'abastecimento_id' => '153']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '695','motivo'=>'1', 'data' => '2023-04-18', 'abastecimento_id' => '154']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '266','motivo'=>'1', 'data' => '2023-04-19', 'abastecimento_id' => '155']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '85','motivo'=>'1', 'data' => '2023-04-19', 'abastecimento_id' => '156']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '71','motivo'=>'1', 'data' => '2023-04-20', 'abastecimento_id' => '157']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '65','motivo'=>'1', 'data' => '2023-04-21', 'abastecimento_id' => '158']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '149','motivo'=>'1', 'data' => '2023-04-22', 'abastecimento_id' => '159']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '279','motivo'=>'1', 'data' => '2023-04-22', 'abastecimento_id' => '160']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '103','motivo'=>'1', 'data' => '2023-04-25', 'abastecimento_id' => '161']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '286','motivo'=>'1', 'data' => '2023-04-26', 'abastecimento_id' => '162']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '12','motivo'=>'1', 'data' => '2023-04-26', 'abastecimento_id' => '163']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '161','motivo'=>'1', 'data' => '2023-04-27', 'abastecimento_id' => '164']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '275','motivo'=>'1', 'data' => '2023-04-28', 'abastecimento_id' => '165']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '124','motivo'=>'1', 'data' => '2023-04-29', 'abastecimento_id' => '166']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '360','motivo'=>'1', 'data' => '2023-05-02', 'abastecimento_id' => '167']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '71','motivo'=>'1', 'data' => '2023-05-03', 'abastecimento_id' => '168']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '360','motivo'=>'1', 'data' => '2023-05-03', 'abastecimento_id' => '169']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '256','motivo'=>'1', 'data' => '2023-05-03', 'abastecimento_id' => '170']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '103','motivo'=>'1', 'data' => '2023-05-08', 'abastecimento_id' => '171']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '128','motivo'=>'1', 'data' => '2023-05-08', 'abastecimento_id' => '172']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '76','motivo'=>'1', 'data' => '2023-05-10', 'abastecimento_id' => '173']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '88', 'produto_id' => '2', 'quantidade' => '202','motivo'=>'1', 'data' => '2023-05-02', 'abastecimento_id' => '174']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '296','motivo'=>'1', 'data' => '2023-05-10', 'abastecimento_id' => '175']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '20', 'produto_id' => '2', 'quantidade' => '204','motivo'=>'1', 'data' => '2023-05-11', 'abastecimento_id' => '176']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '146','motivo'=>'1', 'data' => '2023-05-12', 'abastecimento_id' => '177']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '252','motivo'=>'1', 'data' => '2023-05-13', 'abastecimento_id' => '178']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '126','motivo'=>'1', 'data' => '2023-05-15', 'abastecimento_id' => '179']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '43', 'produto_id' => '2', 'quantidade' => '118','motivo'=>'1', 'data' => '2023-05-15', 'abastecimento_id' => '180']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '42', 'produto_id' => '2', 'quantidade' => '242','motivo'=>'1', 'data' => '2023-05-16', 'abastecimento_id' => '181']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '43', 'produto_id' => '2', 'quantidade' => '100','motivo'=>'1', 'data' => '2023-05-16', 'abastecimento_id' => '182']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '49', 'produto_id' => '2', 'quantidade' => '142','motivo'=>'1', 'data' => '2023-05-18', 'abastecimento_id' => '183']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '43', 'produto_id' => '2', 'quantidade' => '126','motivo'=>'1', 'data' => '2023-05-18', 'abastecimento_id' => '184']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '10','motivo'=>'1', 'data' => '2023-05-18', 'abastecimento_id' => '185']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '43', 'produto_id' => '2', 'quantidade' => '252','motivo'=>'1', 'data' => '2023-05-22', 'abastecimento_id' => '186']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '156','motivo'=>'1', 'data' => '2023-05-23', 'abastecimento_id' => '187']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '608','motivo'=>'1', 'data' => '2023-05-24', 'abastecimento_id' => '188']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '71','motivo'=>'1', 'data' => '2023-05-24', 'abastecimento_id' => '189']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '77', 'produto_id' => '2', 'quantidade' => '4','motivo'=>'1', 'data' => '2023-05-25', 'abastecimento_id' => '190']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '141','motivo'=>'1', 'data' => '2023-05-25', 'abastecimento_id' => '191']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '62', 'produto_id' => '2', 'quantidade' => '160','motivo'=>'1', 'data' => '2023-05-26', 'abastecimento_id' => '192']);
        DB::table('saidas_produtos')->insert(['equipamento_id' => '88', 'produto_id' => '2', 'quantidade' => '90','motivo'=>'1', 'data' => '2023-05-26', 'abastecimento_id' => '193']);
    }
}
