<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedidasTanque1 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => '1', 'medida' => '0', 'quantidade' => '30762']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '1', 'quantidade' => '30747']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '2', 'quantidade' => '30720']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '3', 'quantidade' => '30685']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '4', 'quantidade' => '30643']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '5', 'quantidade' => '30596']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '6', 'quantidade' => '30545']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '7', 'quantidade' => '30489']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '8', 'quantidade' => '30429']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '9', 'quantidade' => '30365']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '10', 'quantidade' => '30296']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '11', 'quantidade' => '30227']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '12', 'quantidade' => '30153']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '13', 'quantidade' => '30076']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '14', 'quantidade' => '29997']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '15', 'quantidade' => '29915']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '16', 'quantidade' => '29830']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '17', 'quantidade' => '29742']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '18', 'quantidade' => '29653']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '19', 'quantidade' => '29561']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '20', 'quantidade' => '29466']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '21', 'quantidade' => '29370']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '22', 'quantidade' => '29271']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '23', 'quantidade' => '29171']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '24', 'quantidade' => '29068']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '25', 'quantidade' => '28964']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '26', 'quantidade' => '28858']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '27', 'quantidade' => '28750']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '28', 'quantidade' => '28640']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '29', 'quantidade' => '28528']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '30', 'quantidade' => '28415']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '31', 'quantidade' => '28300']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '32', 'quantidade' => '28184']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '33', 'quantidade' => '28066']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '34', 'quantidade' => '27947']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '35', 'quantidade' => '27826']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '36', 'quantidade' => '27703']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '37', 'quantidade' => '27580']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '38', 'quantidade' => '27455']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => '1', 'medida' => '39', 'quantidade' => '27328']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => '8', 'unidade_medida_id' => ' 1', 'medida' => '40', 'quantidade' => '27201']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '41', 'quantidade' => '27072']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '42', 'quantidade' => '26942']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '43', 'quantidade' => '26810']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '44', 'quantidade' => '26678']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '45', 'quantidade' => '26544']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '46', 'quantidade' => '26409']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '47', 'quantidade' => '26273']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '48', 'quantidade' => '26136']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '49', 'quantidade' => '25998']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '50', 'quantidade' => '25859']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '51', 'quantidade' => '25719']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '52', 'quantidade' => '25577']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '53', 'quantidade' => '25435']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '54', 'quantidade' => '25299']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '55', 'quantidade' => '25148']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '56', 'quantidade' => '25003']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '57', 'quantidade' => '24858']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '58', 'quantidade' => '24711']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '59', 'quantidade' => '24563']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '60', 'quantidade' => '24415']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '61', 'quantidade' => '24266']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '62', 'quantidade' => '24116']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '63', 'quantidade' => '23966']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '64', 'quantidade' => '23814']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '65', 'quantidade' => '23662']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '66', 'quantidade' => '23509']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '67', 'quantidade' => '23356']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '68', 'quantidade' => '23201']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '69', 'quantidade' => '23047']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '70', 'quantidade' => '22891']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '71', 'quantidade' => '22735']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '72', 'quantidade' => '22578']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '73', 'quantidade' => '22421']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '74', 'quantidade' => '22236']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '75', 'quantidade' => '22104']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '76', 'quantidade' => '21945']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '77', 'quantidade' => '21786']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '78', 'quantidade' => '21626']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '79', 'quantidade' => '21465']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '80', 'quantidade' => '21304']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '81', 'quantidade' => '21142']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '82', 'quantidade' => '20980']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '83', 'quantidade' => '20818']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '84', 'quantidade' => '20655']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '85', 'quantidade' => '20491']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '86', 'quantidade' => '20328']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '87', 'quantidade' => '20164']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '88', 'quantidade' => '19999']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '89', 'quantidade' => '19834']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '90', 'quantidade' => '19669']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '91', 'quantidade' => '19504']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '92', 'quantidade' => '19338']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '93', 'quantidade' => '19172']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '94', 'quantidade' => '19005']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '95', 'quantidade' => '18838']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '96', 'quantidade' => '18671']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '97', 'quantidade' => '18504']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '98', 'quantidade' => '18337']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '99', 'quantidade' => '18169']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '100', 'quantidade' => '18001']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '101', 'quantidade' => '17833']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '102', 'quantidade' => '17665']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '103', 'quantidade' => '17496']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '104', 'quantidade' => '17327']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '105', 'quantidade' => '17159']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '106', 'quantidade' => '16990']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '107', 'quantidade' => '16821']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '108', 'quantidade' => '16652']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '109', 'quantidade' => '16482']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '110', 'quantidade' => '16313']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '111', 'quantidade' => '16144']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '112', 'quantidade' => '15974']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '113', 'quantidade' => '15805']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '114', 'quantidade' => '15635']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '115', 'quantidade' => '15466']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '116', 'quantidade' => '15296']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '117', 'quantidade' => '15127']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '118', 'quantidade' => '14947']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '119', 'quantidade' => '14787']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '120', 'quantidade' => '14618']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '121', 'quantidade' => '14449']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '122', 'quantidade' => '14279']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '123', 'quantidade' => '14110']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '124', 'quantidade' => '13941']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '125', 'quantidade' => '13772']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '126', 'quantidade' => '13603']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '127', 'quantidade' => '13434']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '128', 'quantidade' => '13266']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '129', 'quantidade' => '13097']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '130', 'quantidade' => '12929']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '131', 'quantidade' => '12761']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '132', 'quantidade' => '12593']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '133', 'quantidade' => '12425']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '134', 'quantidade' => '12258']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '135', 'quantidade' => '12090']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '136', 'quantidade' => '11923']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '137', 'quantidade' => '11757']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '138', 'quantidade' => '11590']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '139', 'quantidade' => '11424']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '140', 'quantidade' => '11258']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '141', 'quantidade' => '11093']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '142', 'quantidade' => '10927']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '143', 'quantidade' => '10763']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '144', 'quantidade' => '10598']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '145', 'quantidade' => '10434']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '146', 'quantidade' => '10270']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '147', 'quantidade' => '10107']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '148', 'quantidade' => '9944']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '149', 'quantidade' => '9781']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '150', 'quantidade' => '9619']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '151', 'quantidade' => '9458']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '152', 'quantidade' => '9297']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '153', 'quantidade' => '9136']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '154', 'quantidade' => '8976']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '155', 'quantidade' => '8816']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '156', 'quantidade' => '8657']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '157', 'quantidade' => '8499']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '158', 'quantidade' => '8341']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '159', 'quantidade' => '8184']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '160', 'quantidade' => '8027']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '161', 'quantidade' => '7817']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '162', 'quantidade' => '7715']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '163', 'quantidade' => '7560']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '164', 'quantidade' => '7406']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '165', 'quantidade' => '7252']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '166', 'quantidade' => '7100']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '167', 'quantidade' => '6947']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '168', 'quantidade' => '6796']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '169', 'quantidade' => '6645']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '170', 'quantidade' => '6496']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '171', 'quantidade' => '6346']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '172', 'quantidade' => '6198']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '173', 'quantidade' => '6051']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '174', 'quantidade' => '5094']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '175', 'quantidade' => '5758']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '176', 'quantidade' => '5613']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '177', 'quantidade' => '5469']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '178', 'quantidade' => '5326']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '179', 'quantidade' => '5184']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '180', 'quantidade' => '5043']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '181', 'quantidade' => '4903']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '182', 'quantidade' => '4764']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '183', 'quantidade' => '4626']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '184', 'quantidade' => '4489']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '185', 'quantidade' => '4353']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '186', 'quantidade' => '4218']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '187', 'quantidade' => '4084']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '188', 'quantidade' => '3952']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '189', 'quantidade' => '3820']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '190', 'quantidade' => '3690']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '191', 'quantidade' => '3561']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '192', 'quantidade' => '3433']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '193', 'quantidade' => '3307']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '194', 'quantidade' => '3182']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '195', 'quantidade' => '3058']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '196', 'quantidade' => '2936']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '197', 'quantidade' => '2815']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '198', 'quantidade' => '2696']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '199', 'quantidade' => '2578']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '200', 'quantidade' => '2461']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '201', 'quantidade' => '2347']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '202', 'quantidade' => '2233']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '203', 'quantidade' => '2122']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '204', 'quantidade' => '2012']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '205', 'quantidade' => '1904']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '206', 'quantidade' => '1798']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '207', 'quantidade' => '1693']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '208', 'quantidade' => '1591']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '209', 'quantidade' => '1490']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '210', 'quantidade' => '1392']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '211', 'quantidade' => '1295']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '212', 'quantidade' => '1201']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '213', 'quantidade' => '1109']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '214', 'quantidade' => '1019']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '215', 'quantidade' => '932']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '216', 'quantidade' => '847']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '217', 'quantidade' => '765']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '218', 'quantidade' => '685']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '219', 'quantidade' => '609']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '220', 'quantidade' => '535']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '221', 'quantidade' => '464']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '222', 'quantidade' => '397']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '223', 'quantidade' => '333']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '224', 'quantidade' => '273']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '225', 'quantidade' => '217']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '226', 'quantidade' => '165']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '227', 'quantidade' => '118']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '228', 'quantidade' => '77']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '229', 'quantidade' => '42']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '230', 'quantidade' => '15']);
        DB::table('medidas_tanques')->insert(['equipamento_id' => ' 8', 'unidade_medida_id' => ' 1', 'medida' => '231', 'quantidade' => '0']);
    }
}
